---

- name: check for supported distros
  fail: "{{ ansible_distribution }} is unsupported. Only CentOS and Ubuntu supported."
  when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'CentOS'

# Install packages specific for ubuntu
- name: install prerequisite packages for Ubuntu
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
  when: ansible_distribution == "Ubuntu"
  become: true

# add Docker repo to get the latest docker
- name: add Docker repository for CentOS
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg
  when: ansible_distribution == "CentOS"
  become: true

# add apt key for ubuntu
- name: add Docker APT Key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  when: ansible_distribution == "Ubuntu"
  become: true

- name: add Docker repository
  apt_repository:
    filename: docker
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
  when: ansible_distribution == 'Ubuntu'
  become: true

# install required packages
- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - python
    - docker-engine
  become: true

# install pip
- name: install pip
  shell: >
    curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && python get-pip.py
  args:
    creates: /usr/bin/pip
  become: true

# install docker-py as it is needed by docker-image
- name: install docker-py
  pip:
    name: docker-py
    state: present
  notify: start docker service
  become: true

# install docker-compose as it is needed by docker-image
- name: install docker-compose
  pip:
    name: docker-compose
    state: present
  notify: start docker service
  become: true
